## Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic array slicing:", arr[2:7])

print("\n With Step:", arr[2:8:2])

print("\n Negative Indexing:", arr[-2])



Basic array slicing: [3 4 5 6 7]

 With Step: [3 5 7]

 Negative Indexing: 9


In [6]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific element:", arr_2d[1,2])
print("Entire row elements:", arr_2d[1])
print("Entire row and specific column elements:", arr_2d[:, 2])


Specific element: 6
Entire row elements: [4 5 6]
Entire row and specific column elements: [3 6 9]


## Sorting


In [10]:
unsorted_arr = np.array([2,3,1,7,9,5,4])

print("Sorting: ", np.sort(unsorted_arr))

Sorting:  [1 2 3 4 5 7 9]


In [6]:
unsorted_arr_2d = np.array([[3, 1], [1, 2], [4, 2], [9, 7]])
print("2D Array Sorting: ", np.sort(unsorted_arr_2d, axis=0))


2D Array Sorting:  [[1 1]
 [3 2]
 [4 2]
 [9 7]]


## Filter


In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print("Array filter:", numbers[numbers % 2 == 0])

Array filter: [ 2  4  6  8 10 12]


## Filter with Mask


In [11]:
mask = numbers > 5

print("Numbers grater than 5:", numbers[mask])

Numbers grater than 5: [ 6  7  8  9 10 11 12]


## Fancy indexing vs np.where()

In [15]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 3)
print(where_result)
print("NP Where output:", numbers[where_result])

[1 3 5]
(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]),)
NP Where output: [ 4  5  6  7  8  9 10 11 12]


In [19]:
condition_array = np.where(numbers >5, numbers*2, numbers)

print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20 22 24]


## Adding and Removing Array

In [20]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

combine_arr = np.concatenate((arr1, arr2))
print(combine_arr)

[1 2 3 4 5 6 7 8]


## vstack vs hstack

In [27]:
orignal_arr = np.array([[1,2], [3,4]])
new_row = np.array([5,6])

print(np.vstack((orignal_arr, new_row)))


new_column = np.array([[7], [8]])
print("\n Adding new column:", np.hstack((orignal_arr, new_column)))

##delete

arr = np.array([1,2,3,4,5,6,7])
print("\n Array after delete:", np.delete(arr, 2))

[[1 2]
 [3 4]
 [5 6]]

 Adding new column: [[1 2 7]
 [3 4 8]]

 Array after delete: [1 2 4 5 6 7]
