## Numpy array and Basics


In [2]:
import numpy as np

In [7]:
arr_1d = np.array([1,2,3,4,5])

print("1D Array:", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])

print("2D Array: ", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:  [[1 2 3]
 [4 5 6]]


## List Vs Array


In [10]:
import time

# List
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n Python List operation time: ", time.time() - start)


# Numpy Array
start = time.time()
np_arr = np.arange(1000000) * 2
print("\n Numpy List operation time: ", time.time() - start)


 Python List operation time:  0.05315685272216797

 Numpy List operation time:  0.0018978118896484375


In [23]:
print("zeros array: \n", np.zeros((3,4)))
print("ones array: \n", np.ones((3,4)))
print("full array: \n", np.full((3,4), 5))
print("random array: \n", np.random.random((2,3)))
print("sequence array: \n", np.arange(0, 11, 1))


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random array: 
 [[0.14212732 0.4579156  0.96668061]
 [0.56985233 0.2671541  0.5008354 ]]
sequence array: 
 [ 0  1  2  3  4  5  6  7  8  9 10]


## Vector, Matrics and Tensor

In [24]:
vector =  np.array([1,2,3,4,5])

matrix = np.array([[1,2,3], 
                   [4,5,6]])

tensor = np.array([[[1,2,3], [4,5,6]],
                   [[1,2,3],[4,5,6]]      
                   ])


print("Array shape: ", tensor.shape)
print("Array diamention: ", tensor.ndim)
print("Array size: ", tensor.size)
print("Array Dtype: ", tensor.dtype)


Array shape:  (2, 2, 3)
Array diamention:  3
Array size:  12
Array Dtype:  int64


### Array Reshaping

In [10]:
np_arr = np.arange(12)

print("Original Numpy array - (Vector): ", np_arr)

reshaped = np_arr.reshape((3,4))
print("\n Reshaped array:", reshaped)

flattened = reshaped.flatten()
print("\n Flatten array:", flattened)

# ravel (Retun view instead of copy)
raveled = reshaped.ravel()
print("\n Ravel array:", raveled)

transposed = reshaped.T
print("\n Transpose array:", transposed)


Original Numpy array - (Vector):  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatten array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravel array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
